updated actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,7 +25,14 @@ jobs:
               working-directory: ./backend
               run: |
                   docker compose -f ../docker-compose.testing.yml up -d
+                  SECONDS=0
+                  TIMEOUT=60
                   while [ ! -f ./__generated__endpoints.json ]; do
+                      if [ $SECONDS -ge $TIMEOUT ]; then
+                          echo "Timeout reached: __generated__endpoints.json not found"
+                          exit 1
+                      fi
                       sleep 1
+                      echo "waiting for endpoints"
                   done
                   yarn test
